#include "pingkk/language.h"

#include <map>
#include <string>

namespace pingkk {
namespace {
bool english = false;
}  // namespace

void setEnglish(bool enabled) {
    english = enabled;
}

const char* text(const char* chinese) {
    if (!english) return chinese;
    static const std::map<std::string, const char*> translations = {
        {"未找到图形界面，请下载适合当前系统的图形界面包或安装包：\n", "The graphical interface was not found. Download the GUI package or installer for your system:\n"},
        {"2. 网站下载：https://he.sb/pingkk/\n", "2. Website: https://he.sb/pingkk/\n"},
        {"图形界面启动失败，请检查安装文件和运行环境。\n", "The graphical interface could not be started. Check the installation files and runtime environment.\n"},
        {"目标没有可用的 IPv6 地址", "The target has no usable IPv6 address"},
        {"目标没有可用的 IPv4 地址", "The target has no usable IPv4 address"},
        {"无法确定 IPv6 本机出口地址", "Unable to determine the local IPv6 outbound address"},
        {"IPv6 数据包超过路径 MTU", "IPv6 packet exceeds the path MTU"},
        {"IPv6 数据包参数错误", "Invalid IPv6 packet parameters"},
        {" 字节，IPv6 包：", " bytes, IPv6 packet: "},
        {"  前缀：", "  Prefix: "},
        {"  [跳过] 没有所选地址类型的解析结果。\n", "  [Skipped] No address of the selected IP version was resolved.\n"},
        {"-v6 和 -v46 不能同时使用。\n", "-v6 and -v46 cannot be combined.\n"},
        {"    -v6                             使用 IPv6，默认 IPv4\n", "    -v6                                Use IPv6 (default: IPv4)\n"},
        {"    -v46                            同时测试 IPv4 和 IPv6\n", "    -v46                               Test both IPv4 and IPv6\n"},
        {"结论：公共 DNS 均未返回所选地址类型的记录。域名可能存在，", "Conclusion: No public DNS resolver returned records for the selected IP version. The domain may exist, "},
        {"但当前没有配置可用于访问的所选类型地址。\n", "but it currently has no addresses of the selected IP version configured for access.\n"},

        {"一次只能测试一个目标地址。", "Test one target address at a time."},
        {"只能指定一个协议：tcp、udp 或 all。", "Specify only one protocol: tcp, udp, or all."},
        {"请指定一组 1 到 65535 之间的端口，多个端口用逗号分隔。", "Specify one list of ports between 1 and 65535, separated by commas."},
        {"无法识别参数：", "Unrecognized argument: "},
        {"。请只填写一个目标地址、数字端口和 tcp、udp 或 all 协议。", ". Use one target address, numeric ports, and a tcp, udp, or all protocol."},
        {"指定协议时需要同时填写端口。", "A port is required when specifying a protocol."},
        {"未知选项：", "Unknown option: "},
        {"路由追踪、网络检查和 DNS 对比不能同时使用。\n", "Traceroute, network check, and DNS comparison cannot be combined.\n"},
        {"持续测试只能用于 Ping 或端口测试。\n", "Continuous testing is available only for Ping and port tests.\n"},

        {"  掩码：", "  Subnet mask: "},
        {"域名解析暂时失败，请稍后重试", "DNS lookup temporarily failed. Try again later."},
        {"未找到该域名，请检查地址是否正确", "Domain not found. Check the address."},
        {"该域名没有可用的 IP 地址", "The domain has no usable IP address."},
        {"域名解析服务器返回错误", "The DNS server returned an error."},
        {"域名解析失败，请检查网络或 DNS 设置", "DNS lookup failed. Check your network or DNS settings."},
        {"域名解析失败，请检查地址和网络设置", "DNS lookup failed. Check the address and network settings."},
        {"系统错误 ", "System error "},
        {"目标地址为空或格式不正确", "The target address is empty or invalid."},
        {"网络组件初始化失败", "Network initialization failed."},
        {"解析结果中没有可用的 IP 地址", "No usable IP address was found."},
        {"未知", "Unknown"},
        {"无法创建目标地址", "Unable to create the target address."},
        {"无法创建 TCP 连接", "Unable to create a TCP connection."},
        {"连接成功", "Connected"},
        {"连接超时", "Connection timed out"},
        {"无法创建 UDP 探测", "Unable to create a UDP probe."},
        {"收到 UDP 响应", "UDP response received"},
        {"探测已发送，未收到响应", "Probe sent; no response received"},
        {"请求超时", "Request timed out"},
        {"TTL 已过期", "TTL expired"},
        {"目标主机不可达", "Destination host unreachable"},
        {"目标网络不可达", "Destination network unreachable"},
        {"ICMP 状态 ", "ICMP status "},
        {"IPv4 地址无效", "Invalid IPv4 address."},
        {"无法创建 ICMP 探测", "Unable to create an ICMP probe."},
        {"ICMP 探测失败", "ICMP probe failed"},
        {"系统不允许当前用户发送 ICMP，请授予网络诊断权限", "ICMP is not permitted for this user. Grant network diagnostic permissions."},
        {"探测已中断", "Probe interrupted"},
        {"DNS 服务器地址无效", "Invalid DNS server address"},
        {"域名格式不正确", "Invalid domain name"},
        {"无法创建 DNS 查询", "Unable to create a DNS query"},
        {"无法连接 DNS 服务器", "Unable to connect to the DNS server"},
        {"DNS 查询发送失败", "Unable to send the DNS query"},
        {"查询超时", "Query timed out"},
        {"DNS 查询失败", "DNS query failed"},
        {"DNS 响应无效", "Invalid DNS response"},
        {"收到的 DNS 数据不是响应", "The received DNS packet is not a response"},
        {"DNS 响应被截断", "DNS response truncated"},
        {"域名不存在（NXDOMAIN）", "Domain does not exist (NXDOMAIN)"},
        {"DNS 返回错误码 ", "DNS returned error code "},
        {"DNS 响应中的查询数量不正确", "Unexpected question count in the DNS response"},
        {"DNS 响应格式错误", "Malformed DNS response"},
        {"DNS 响应与查询不匹配", "DNS response does not match the query"},
        {"没有返回 A 记录", "No A records returned"},
        {"没有返回 AAAA 记录", "No AAAA records returned"},
        {"系统 DNS", "System DNS"},
        {"自动", "Automatic"},
        {"系统解析失败", "System DNS lookup failed"},
        {"没有返回 A 或 AAAA 记录", "No A or AAAA records returned"},
        {"当前 DNS", "Current DNS"},
        {"阿里 DNS", "Alibaba DNS"},
        {"腾讯 DNS", "Tencent DNS"},
        {"系统 HTTP", "System HTTP"},
        {"系统 HTTPS", "System HTTPS"},
        {"系统 SOCKS", "System SOCKS"},
        {"系统代理=", "System proxy="},
        {"系统自动代理检测=已启用", "System proxy auto-detection=enabled"},
        {"系统 PAC=已启用", "System PAC=enabled"},
        {"当前 DNS：未检测到\n", "Current DNS: none detected\n"},
        {"当前 DNS：", "Current DNS: "},
        {"ping看看（pingkk）v", "pingkk v"},
        {" 端口连通性测试工具\n", " Port Connectivity Tester\n"},
        {"项目地址：", "Project: "},
        {"用法：\n", "Usage:\n"},
        {"  完整请求：\n", "  Commands:\n"},
        {"  pingkk <地址> <端口> [tcp|udp|all]   测试一次端口\n", "  pingkk <address> <ports> [tcp|udp|all]  Test ports once\n"},
        {"  pingkk <地址>                      执行 Ping 测试 4 次\n", "  pingkk <address>                      Send 4 Ping probes\n"},
        {"  pingkk -r, --route <地址>          路由追踪（不解析节点域名）\n", "  pingkk -r, --route <address>           Trace the route without resolving hop names\n"},
        {"  pingkk -jc, --checkup              一键网络检查\n", "  pingkk -jc, --checkup                  Run a network check\n"},
        {"  pingkk --dns <域名>                对比系统、当前及公共 DNS\n", "  pingkk --dns <domain>                 Compare system, current, and public DNS\n"},
        {"  额外附加参数：\n", "  Additional options:\n"},
        {"    -a, --advanced                  输出更详细的诊断信息\n", "    -a, --advanced                     Show detailed diagnostics\n"},
        {"    --timeout <毫秒>                设置超时时间，默认 1000\n", "    --timeout <milliseconds>           Set the timeout (default: 1000)\n"},
        {"    -t                              持续测试\n", "    -t                                 Test continuously\n"},
        {"    --lang <zh|en>                  设置输出语言，默认 zh\n", "    --lang <zh|en>                      Set the output language (default: zh)\n"},
        {"  pingkk gui                        打开图形界面\n", "  pingkk gui                           Open the graphical interface\n"},
        {"  pingkk -h | --help                 显示本教程\n\n", "  pingkk -h | --help                    Show this help\n\n"},
        {"额外附加参数可以放在命令中的任意位置；--timeout 和 --lang 的值需紧跟对应选项。\n", "Additional options can appear anywhere; values for --timeout and --lang must immediately follow the option.\n"},
        {"一次只能测试一个地址；多个端口使用英文逗号分隔。\n", "Test one address at a time. Separate multiple ports with commas.\n"},
        {"地址可以填写 IP、域名或完整网址，例如：https://example.com/path\n", "Use an IP address, domain, or full URL, such as https://example.com/path\n"},
        {"UDP 只有收到目标响应时才能确认连通；无响应不等于端口不通。\n", "UDP connectivity is confirmed only when a response is received. No response does not mean the port is unreachable.\n"},
        {"[高级信息]\n", "[Advanced details]\n"},
        {"  原始输入：", "  Input: "},
        {"  解析主机：", "  Host: "},
        {"  目标 IP：", "  Target IP: "},
        {"  地址类型：", "  Address type: "},
        {"  本机出口 IP：", "  Local outbound IP: "},
        {"  测试模式：", "  Test mode: "},
        {"  超时时间：", "  Timeout: "},
        {" 毫秒\n", " ms\n"},
        {"[高级统计] ", "[Advanced statistics] "},
        {"  已发送：", "  Sent: "},
        {"，已响应：", ", received: "},
        {"，丢失：", ", lost: "},
        {"  往返时延：最小 ", "  Round-trip time: min "},
        {" 毫秒，最大 ", " ms, max "},
        {" 毫秒，平均 ", " ms, average "},
        {" 毫秒，波动 ", " ms, standard deviation "},
        {"[高级统计] 端口测试汇总\n", "[Advanced statistics] Port test summary\n"},
        {"  总次数：", "  Attempts: "},
        {"，连通：", ", reachable: "},
        {"，不通：", ", unreachable: "},
        {"，状态未知：", ", unknown: "},
        {"  连通耗时：最小 ", "  Connection time: min "},
        {"域名格式不正确。\n", "Invalid domain name.\n"},
        {"正在对比 ", "Comparing DNS results for "},
        {" 的 DNS 解析结果：\n", ":\n"},
        {"  查询域名：", "  Domain: "},
        {"  查询记录：A、AAAA\n", "  Record types: A, AAAA\n"},
        {"  单次超时：", "  Query timeout: "},
        {"  对比来源：系统 DNS、当前 DNS、阿里 DNS、腾讯 DNS\n", "  Resolvers: system DNS, current DNS, Alibaba DNS, Tencent DNS\n"},
        {"没有可用的 DNS 服务器。\n", "No DNS servers are available.\n"},
        {"[正常] ", "[OK] "},
        {"[失败] ", "[Failed] "},
        {"毫秒\n", " ms\n"},
        {"[高级统计] DNS 查询汇总\n", "[Advanced statistics] DNS query summary\n"},
        {"  解析器：", "  Resolvers: "},
        {"，成功：", ", succeeded: "},
        {"，失败：", ", failed: "},
        {"，公共 DNS 返回 NXDOMAIN：", ", public DNS NXDOMAIN responses: "},
        {"，无 A/AAAA 记录：", ", no A/AAAA records: "},
        {"  查询耗时：最小 ", "  Query time: min "},
        {"结论：DNS 解析结果存在差异。系统或当前 DNS 可以解析，", "Conclusion: DNS results differ. System or current DNS resolves the domain, "},
        {"但公共 DNS 返回域名不存在（NXDOMAIN）。可能原因包括内网或分区 DNS、", "but public DNS returns NXDOMAIN. Possible causes include private or split DNS, "},
        {"DNS 拦截/过滤，或公网记录尚未同步；仅凭本次检测无法断定该域名只能在当前网络使用。\n", "DNS interception or filtering, or public records that have not propagated. This test alone cannot determine whether the domain is limited to this network.\n"},
        {"结论：公共 DNS 均未返回 A 或 AAAA 记录。域名可能存在，", "Conclusion: No public DNS resolver returned A or AAAA records. The domain may exist, "},
        {"但当前没有配置可用于访问的 IPv4 或 IPv6 地址。\n", "but it currently has no IPv4 or IPv6 addresses configured for access.\n"},
        {"结论：所有 DNS 查询均失败，请检查网络、防火墙或 DNS 设置。\n", "Conclusion: All DNS queries failed. Check your network, firewall, or DNS settings.\n"},
        {"结论：部分 DNS 查询失败，不能判定结果一致；", "Conclusion: Some DNS queries failed, so consistency cannot be determined; "},
        {" 个解析器成功，", " resolvers succeeded, "},
        {" 个失败。\n", " failed.\n"},
        {"结论：不同 DNS 返回的 IP 不完全一致；CDN 调度可能导致差异，如访问异常请优先检查系统 DNS。\n", "Conclusion: DNS resolvers returned different IP addresses. CDN routing may explain the differences. If access fails, check system DNS first.\n"},
        {"结论：各 DNS 返回结果一致。\n", "Conclusion: All DNS resolvers returned consistent results.\n"},
        {"开始一键网络检查……\n\n", "Starting network check...\n\n"},
        {"  基准域名：baidu.com\n", "  Reference domain: baidu.com\n"},
        {"  HTTPS 目标端口：443\n", "  HTTPS target port: 443\n"},
        {"  单项超时：", "  Timeout per check: "},
        {" 毫秒\n\n", " ms\n\n"},
        {"[1/5] 本机网络\n", "[1/5] Local network\n"},
        {"  IP：", "  IP: "},
        {"  网关：", "  Gateway: "},
        {"[2/5] DNS 配置\n", "[2/5] DNS configuration\n"},
        {"  DNS：", "  DNS: "},
        {"[3/5] 代理设置\n", "[3/5] Proxy settings\n"},
        {"  未检测到已启用的代理。\n", "  No enabled proxies detected.\n"},
        {"[4/5] 域名解析（baidu.com）\n", "[4/5] Domain resolution (baidu.com)\n"},
        {"  [失败] 系统 DNS 无法解析 baidu.com：", "  [Failed] System DNS could not resolve baidu.com: "},
        {"  [正常] 系统 DNS：", "  [OK] System DNS: "},
        {"毫秒，IP ", " ms, IP "},
        {"[5/5] HTTPS 直连（baidu.com）\n", "[5/5] Direct HTTPS connection (baidu.com)\n"},
        {"  [跳过] 没有可用的 IPv4 解析结果。\n", "  [Skipped] No usable IPv4 address was resolved.\n"},
        {"[高级统计] 检查汇总\n", "[Advanced statistics] Network check summary\n"},
        {"  DNS 服务器：", "  DNS servers: "},
        {"，已启用代理：", ", enabled proxies: "},
        {"  DNS 解析耗时：", "  DNS lookup time: "},
        {"  总耗时：", "  Total time: "},
        {"\n检查结论：", "\nNetwork check conclusion: "},
        {"基础网络状态正常。", "Basic network checks passed."},
        {"发现异常，请根据上方失败项目继续排查。", "Problems detected. Review the failed checks above."},
        {"目标地址格式不正确。\n", "Invalid target address.\n"},
        {"无法解析 ", "Unable to resolve "},
        {"路由追踪", "Traceroute"},
        {"持续 Ping", "Continuous Ping"},
        {"域名 ", "Domain "},
        {" 解析为 IP ", " resolved to IP "},
        {"[高级统计] 路由追踪汇总\n", "[Advanced statistics] Traceroute summary\n"},
        {"  已探测跳数：", "  Hops probed: "},
        {"，有响应：", ", responded: "},
        {"，无响应：", ", no response: "},
        {"正在追踪到 ", "Tracing route to "},
        {" 的路由，最多 30 跳：\n", ", up to 30 hops:\n"},
        {"毫秒", " ms"},
        {"路由追踪完成。\n", "Traceroute complete.\n"},
        {"已达到最大跳数，目标尚未响应。\n", "Maximum hop count reached without a response from the target.\n"},
        {"正在 Ping ", "Pinging "},
        {"来自 ", "Reply from "},
        {"：时间=", ": time="},
        {" 序号=", " seq="},
        {" 数据=", " payload="},
        {"字节", " bytes"},
        {" IP包=", " IP packet="},
        {"序号=", "seq="},
        {"字节\n", " bytes\n"},
        {"Ping 汇总", "Ping summary"},
        {"  ICMP 数据：", "  ICMP payload: "},
        {" 字节，IPv4 包：", " bytes, IPv4 packet: "},
        {" 字节（不含链路层开销）\n", " bytes (excluding link-layer overhead)\n"},
        {"对 ", "Testing "},
        {" 的 ", " port "},
        {" 端口测试", " connectivity"},
        {" 协议", " protocol "},
        {"连通", "reachable"},
        {"状态未知", "unknown"},
        {"不通", "unreachable"},
        {"毫秒）\n", " ms)\n"},
        {"超时时间必须是 100 到 60000 之间的毫秒数。\n", "Timeout must be between 100 and 60000 milliseconds.\n"},
        {"缺少目标地址。\n", "Missing target address.\n"},
        {"一键网络检查不需要目标地址。\n", "Network check does not require a target address.\n"},
        {"DNS 对比需要一个域名。\n", "DNS comparison requires one domain name.\n"},
        {"一次只能测试一个目标地址。\n", "Test one target address at a time.\n"},
        {"持续测试不能与路由追踪同时使用。\n", "Continuous testing cannot be combined with traceroute.\n"},
        {"路由追踪只需要目标地址。\n", "Traceroute requires only a target address.\n"},
        {"参数数量不正确，请运行 pingkk --help 查看用法。\n", "Invalid number of arguments. Run pingkk --help for usage.\n"},
        {"端口必须是 1 到 65535 之间的数字，多个端口请使用英文逗号分隔。\n", "Ports must be between 1 and 65535. Separate multiple ports with commas.\n"},
        {"协议只能是 tcp、udp 或 all。\n", "Protocol must be tcp, udp, or all.\n"},
        {"无法解析目标地址：", "Unable to resolve the target address: "},
        {"TCP 端口测试", "TCP port test"},
        {"UDP 端口测试", "UDP port test"},
        {"TCP + UDP 端口测试", "TCP + UDP port test"},
        {"持续", "Continuous "},
        {"  目标端口：", "  Target ports: "},
        {"当前 IP：", "Local IP: "},
        {"；", "; "},
        {"（", " ("},
        {"）", ")"},
        {"：\n", ":\n"},
        {"：", ": "},
        {"，", ", "},
        {"%）\n", "%)\n"},
        {"  IPv4：", "  IPv4: "},
        {"  IPv6：", "  IPv6: "},
    };
    const std::map<std::string, const char*>::const_iterator found = translations.find(chinese);
    return found == translations.end() ? chinese : found->second;
}

}  // namespace pingkk
